[package]
name = "example_stream_object"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rai_ai = { workspace = true }
rai_chatgpt = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
