[package]
name = "example_generate_object"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
rs_ai_core = { workspace = true }
rs_ai_providers = { workspace = true, features = ["chatgpt"] }
tokio = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
